name: test
on:
  - push
  - pull_request
  - workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{
      (github.event_name != 'pull_request' || github.event.action != 'synchronize') }}
    steps:
      - name: Checkout code from repository
        uses: actions/checkout@v2
      - name: Use Node.js lts
        uses: actions/setup-node@v2
        with:
          node-version: "lts/*"
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install
      - name: Build
        run: yarn run build
      - name: Test
        run: yarn run test
